import express, { Request, Response, NextFunction } from 'express';
import { DatabaseClient } from '../db/client.ts';
import { DiscoveryBusinessRepository } from '../repositories/discoveryBusinessRepository.ts';
import { DiscoveryBusinessService } from '../services/discoveryBusinessService.ts';
import { requireAuth } from '../middleware/auth.ts';
import { assertBusinessPermission, type DiscoveryBusinessPermission } from '../services/discoveryBusinessAccess.ts';

export function createDiscoveryBusinessRouter(db: DatabaseClient) {
  const router = express.Router(); const repo = new DiscoveryBusinessRepository(db); const service = new DiscoveryBusinessService(repo, db);
  const actor=(req:Request)=>({userId:req.auth!.userId,role:req.auth!.role,organizationId:req.auth!.organizationId});
  const owned=async(req:Request,id:string,permission:DiscoveryBusinessPermission='business.listing.manage')=>{if(req.auth?.role==='super_admin')return true;try{await assertBusinessPermission(db,id,req.auth!.userId,permission);return true;}catch{return false;}};
  const fail=(res:Response,err:any)=>{const message=String(err?.message||'Discovery request failed.');const code=message.split(':')[0];const status=['NOT_FOUND','DISCOVERY_BUSINESS_NOT_FOUND'].includes(code)?404:['PERMISSION_DENIED','INACTIVE_ORGANIZATION','TENANT_ACCESS_DENIED'].includes(code)?403:code.startsWith('VALIDATION_ERROR')?422:['INVALID_STATE_TRANSITION','DISCOVERY_INVALID_LIFECYCLE'].includes(code)?409:400;return res.status(status).json({success:false,error:{code,message:message.includes(':')?message.slice(message.indexOf(':')+1).trim():message}});};
  router.get('/businesses',async(req,res,next)=>{try{const data=await service.listPublished({city:typeof req.query.city==='string'?req.query.city:undefined,district:typeof req.query.district==='string'?req.query.district:undefined,region:typeof req.query.region==='string'?req.query.region:undefined,businessType:typeof req.query.businessType==='string'?req.query.businessType:undefined,categoryId:typeof req.query.categoryId==='string'?req.query.categoryId:undefined,limit:typeof req.query.limit==='string'?Number(req.query.limit):undefined,offset:typeof req.query.offset==='string'?Number(req.query.offset):undefined});res.json({success:true,count:data.length,data});}catch(e){next(e);}});
  router.get('/businesses/my',requireAuth(),async(req,res,next)=>{try{const result=await db.query(`SELECT b.*,m.role AS membership_role FROM discovery_businesses b JOIN discovery_business_memberships m ON m.business_id=b.id WHERE m.user_id=$1 AND m.is_active=TRUE ORDER BY b.created_at DESC`,[req.auth!.userId]);res.json({success:true,count:result.rows.length,data:result.rows});}catch(e){next(e);}});
  router.get('/businesses/:slug',async(req,res,next)=>{try{const b=await service.getBySlug(req.params.slug,true);if(!b)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Business listing not found.'}});res.json({success:true,data:await service.getPublicProfile(b.id)});}catch(e){next(e);}});
  router.post('/businesses',requireAuth(),async(req,res,next)=>{try{const organizationId=req.body?.organizationId===undefined?req.auth!.organizationId:String(req.body.organizationId||'');if(req.auth!.role!=='super_admin'&&organizationId!==req.auth!.organizationId)return res.status(403).json({success:false,error:{code:'TENANT_ACCESS_DENIED',message:'Cross-tenant discovery business creation forbidden.'}});const data=await service.create({...req.body,organizationId:organizationId||null,createdByUserId:req.auth!.userId},actor(req));res.status(201).json({success:true,data});}catch(e){next(e);}});
  // Discovery-only listings have no tenant, so tenant middleware must not block their owner from editing.
  // The service remains authoritative for ownership and organization-attachment authorization.
  router.patch('/businesses/:id',requireAuth(),async(req,res,next)=>{try{if(!(await owned(req,req.params.id,'business.listing.manage')))return res.status(403).json({success:false,error:{code:'TENANT_ACCESS_DENIED',message:'Cross-tenant discovery business modification forbidden.'}});res.json({success:true,data:await service.update(req.params.id,req.body,actor(req))});}catch(e){next(e);}});
  router.post('/businesses/:id/submit',requireAuth(),async(req,res,next)=>{try{if(!(await owned(req,req.params.id,'business.listing.submit')))return res.status(403).json({success:false,error:{code:'TENANT_ACCESS_DENIED',message:'Cross-tenant submission forbidden.'}});res.json({success:true,data:await service.submit(req.params.id,actor(req),req.body?.reason)});}catch(e){next(e);}});
  router.get('/businesses/:id/management',requireAuth(),async(req,res,next)=>{try{res.json({success:true,data:await service.getListingManagementWorkspace(req.params.id,actor(req))});}catch(e){next(e);}});
  router.post('/businesses/:id/resubmit',requireAuth(),async(req,res,next)=>{try{if(!(await owned(req,req.params.id,'business.listing.submit')))return res.status(403).json({success:false,error:{code:'TENANT_ACCESS_DENIED',message:'Cross-tenant resubmission forbidden.'}});res.json({success:true,data:await service.resubmit(req.params.id,actor(req),req.body?.reason)});}catch(e){next(e);}});

  router.post('/businesses/:id/approve',requireAuth(),async(req,res,next)=>{try{res.json({success:true,data:await service.approve(req.params.id,actor(req),req.body?.reason)});}catch(e){next(e);}});
  router.post('/businesses/:id/publish',requireAuth(),async(req,res,next)=>{try{res.json({success:true,data:await service.publish(req.params.id,actor(req),req.body?.reason)});}catch(e){next(e);}});
  router.post('/businesses/:id/pause',requireAuth(),async(req,res,next)=>{try{if(!(await owned(req,req.params.id,'business.listing.manage')))return res.status(403).json({success:false,error:{code:'TENANT_ACCESS_DENIED',message:'Cross-tenant operation forbidden.'}});res.json({success:true,data:await service.pause(req.params.id,actor(req),req.body?.reason)});}catch(e){next(e);}});
  router.post('/businesses/:id/suspend',requireAuth(),async(req,res,next)=>{try{res.json({success:true,data:await service.suspend(req.params.id,actor(req),req.body?.reason)});}catch(e){next(e);}});
  router.post('/businesses/:id/archive',requireAuth(),async(req,res,next)=>{try{if(!(await owned(req,req.params.id)))return res.status(403).json({success:false,error:{code:'TENANT_ACCESS_DENIED',message:'Cross-tenant operation forbidden.'}});res.json({success:true,data:await service.archive(req.params.id,actor(req),req.body?.reason)});}catch(e){next(e);}});
  router.use((err:any,_req:Request,res:Response,next:NextFunction)=>res.headersSent?next(err):fail(res,err)); return router;
}
